#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorNone)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           upMotor,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           downMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           intakeMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           deployMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           liftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

//CONSTANTS TO ADAPT THE CODE TO THE STARSTRUCK COMPETITION
//If the robot is using VexNetUpgrade the lines can be commented out
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

//CONSTANTS FOR MOVEMENT MANAGEMENT
// Controller 1/2, Stick L/R, Axis X/Y
#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]
#define FL upMotor
#define FR rightMotor
#define BL leftMotor
#define BR downMotor

#define SPEED_MOTORS 60
#define SUPER_SPEED_MOTORS 127

//CONSTANTS FOR AUTONOMOUS MODE
int AUTO_FORWARD_DISTANCE = 1491;
int AUTO_RIGHT_TIME = 3200; //TODO: Adjust values on a real game field

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...

  //TODO: Reset wheel sensor


}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task shakeClaw()
{
	while (true)
	{
		startMotor(intakeMotor, SUPER_SPEED_MOTORS);
		waitInMilliseconds(1000);
		startMotor(intakeMotor, -SUPER_SPEED_MOTORS);
		waitInMilliseconds(1000);
	}
}

task autonomous()
{
  // ..........................................................................
	startMotor(leftMotor, SPEED_MOTORS);
  startMotor(rightMotor, -SPEED_MOTORS);
	startMotor(liftMotor, SUPER_SPEED_MOTORS);

  waitInMilliseconds(3000);

	stopMotor(leftMotor);
	stopMotor(rightMotor);
	stopMotor(liftMotor);

	startMotor(liftMotor, SUPER_SPEED_MOTORS);
  waitInMilliseconds(2000);
	stopMotor(liftMotor);

	// DEPENDING OF THE POSITION - TO THE LEFT OR TO THE RIGHT (FLIP SIGNS)
	startMotor(upMotor, SPEED_MOTORS);
	startMotor(downMotor, -SPEED_MOTORS);
	startTask(shakeClaw);
	waitInMilliseconds(6000);


}

task goForward()
{
  // ..........................................................................
	startMotor(leftMotor, SPEED_MOTORS);
  startMotor(rightMotor, -SPEED_MOTORS);
}

task goBackwards()
{
  // ..........................................................................
	startMotor(leftMotor, -SPEED_MOTORS);
  startMotor(rightMotor, SPEED_MOTORS);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
		// SOURCE CODE: https://www.vexforum.com/index.php/12370-holonomic-drives-2-0-a-video-tutorial-by-cody/0

		// MOVEMENT
		// Y component, X component, Rotation
		motor[FL] = -C1LY - C1LX - C1RX;
		motor[FR] =  C1LY - C1LX - C1RX;
		motor[BR] =  C1LY + C1LX - C1RX;
		motor[BL] = -C1LY + C1LX - C1RX;

		// INTAKE
		if (vexRT[Btn6U] == 1)
			motor[intakeMotor] = -SPEED_MOTORS-40;//20
		else if (vexRT[Btn6D] == 1)
			motor[intakeMotor] = SPEED_MOTORS+40;//20
		else
			motor[intakeMotor] = 0;

		// LIFT
		if (vexRT[Btn5U] == 1)
			motor[liftMotor] = SUPER_SPEED_MOTORS; //SPEED_MOTORS+20;
		else if (vexRT[Btn5D] == 1)
			motor[liftMotor] = -SUPER_SPEED_MOTORS; //-SPEED_MOTORS;
		else
			motor[liftMotor] = 0;

		// DEPLOY SYSTEM
		if (vexRT[Btn8U] == 1)
			motor[deployMotor] = SUPER_SPEED_MOTORS; //SPEED_MOTORS+60;//40
		else if (vexRT[Btn8D] == 1)
			motor[deployMotor] = -SUPER_SPEED_MOTORS; //-SPEED_MOTORS-60;//-40
		else
			motor[deployMotor] = 0;

		// TEST AUTONOMOUS MODE
		if (vexRT[Btn7L] == 1)
			startTask(autonomous);

		// TEST BUTTON
		if (vexRT[Btn7R] == 1)
	{
	startMotor(upMotor, SPEED_MOTORS);
	startMotor(downMotor, -SPEED_MOTORS);
	}

		// GO FORWARD AND BACKWARDS
		if (vexRT[Btn7U] == 1)
			startTask(goForward);
		else if (vexRT[Btn7D] == 1)
			startTask(goBackwards);
		else
		{
			stopMotor(leftMotor);
			stopMotor(rightMotor);
		}

		// Motor values can only be updated every 20ms
		wait1Msec(20);
  }
}
